"use client";

import { useState } from "react";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import type { ExecutiveSummaryPayload } from "@/lib/summary";
import { buildTemplatedSummary } from "@/lib/summary";

// ---------------------------------------------------------------------
// Phase 3d: "Generate executive summary" button. Calls the server-side
// /api/summary route (never the LLM provider directly from the browser --
// the API key stays server-only) with the small aggregate payload already
// computed for the current filters. Always resolves to SOME text: either
// the LLM's response, or a templated fallback if no key is configured or
// the call fails for any reason (network error, timeout, non-200, etc.).
// ---------------------------------------------------------------------

type State =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "done"; text: string; source: "llm" | "template" }
  | { status: "error"; text: string };

export default function ExecutiveSummary({ payload }: { payload: ExecutiveSummaryPayload }) {
  const [state, setState] = useState<State>({ status: "idle" });

  async function handleClick() {
    setState({ status: "loading" });
    try {
      const res = await fetch("/api/summary", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error(`status ${res.status}`);
      const data = await res.json();
      if (typeof data.text !== "string") throw new Error("malformed response");
      setState({ status: "done", text: data.text, source: data.source === "llm" ? "llm" : "template" });
    } catch {
      // Network entirely unreachable, route missing, etc. -- fall back to
      // the same templated summary client-side so the button never shows
      // a broken state.
      setState({ status: "done", text: buildTemplatedSummary(payload), source: "template" });
    }
  }

  return (
    <Box>
      <Box sx={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: "16px", flexWrap: "wrap" }}>
        <Box>
          <Typography component="h3" sx={{ fontFamily: "var(--font-serif)", fontSize: "0.98rem", fontWeight: 600, m: 0, color: "text.primary" }}>
            Executive summary
          </Typography>
          <Typography sx={{ fontSize: "0.8rem", color: "text.secondary", mt: "2px" }}>
            A short, plain-language recap of the current filter selection.
          </Typography>
        </Box>
        <Button
          variant="outlined"
          size="small"
          onClick={handleClick}
          disabled={state.status === "loading"}
          sx={{ flexShrink: 0 }}
        >
          {state.status === "loading" ? "Generating..." : "Generate executive summary"}
        </Button>
      </Box>

      {state.status === "done" && (
        <Box sx={{ mt: "14px", pt: "14px", borderTop: "1px dashed", borderColor: "divider" }}>
          <Typography sx={{ fontSize: "0.9rem", lineHeight: 1.65, color: "text.primary", m: 0 }}>
            {state.text}
          </Typography>
          <Typography sx={{ mt: "8px", fontSize: "0.72rem", color: "text.disabled", fontStyle: "italic" }}>
            {state.source === "llm"
              ? "Content generated by an LLM -- always verify its output."
              : "Generated from the numbers above (no AI model configured for this run)."}
          </Typography>
        </Box>
      )}
    </Box>
  );
}
