"use client";

import { useState } from "react";
import type { ExecutiveSummaryPayload } from "@/lib/summary";
import { buildTemplatedSummary } from "@/lib/summary";

// ---------------------------------------------------------------------
// Phase 3d: "Generate executive summary" button. Calls the server-side
// /api/summary route (never the LLM provider directly from the browser --
// the API key stays server-only) with the small aggregate payload already
// computed for the current filters. Always resolves to SOME text: either
// the LLM's response, or a templated fallback if no key is configured or
// the call fails for any reason (network error, timeout, non-200, etc.).
// ---------------------------------------------------------------------

type State =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "done"; text: string; source: "llm" | "template" }
  | { status: "error"; text: string };

export default function ExecutiveSummary({ payload }: { payload: ExecutiveSummaryPayload }) {
  const [state, setState] = useState<State>({ status: "idle" });

  async function handleClick() {
    setState({ status: "loading" });
    try {
      const res = await fetch("/api/summary", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error(`status ${res.status}`);
      const data = await res.json();
      if (typeof data.text !== "string") throw new Error("malformed response");
      setState({ status: "done", text: data.text, source: data.source === "llm" ? "llm" : "template" });
    } catch {
      // Network entirely unreachable, route missing, etc. -- fall back to
      // the same templated summary client-side so the button never shows
      // a broken state.
      setState({ status: "done", text: buildTemplatedSummary(payload), source: "template" });
    }
  }

  return (
    <div className="exec-summary">
      <div className="exec-summary-head">
        <div>
          <h3 className="rec-title">Executive summary</h3>
          <p className="panel-subtitle" style={{ marginTop: 2 }}>
            A short, plain-language recap of the current filter selection.
          </p>
        </div>
        <button
          className="reset-btn"
          onClick={handleClick}
          disabled={state.status === "loading"}
        >
          {state.status === "loading" ? "Generating..." : "Generate executive summary"}
        </button>
      </div>

      {state.status === "done" && (
        <div className="exec-summary-body">
          <p>{state.text}</p>
          <p className="exec-summary-source">
            {state.source === "llm"
              ? "Generated by a free-tier AI model."
              : "Generated from the numbers above (no AI model configured for this run)."}
          </p>
        </div>
      )}
    </div>
  );
}
